#!/bin/bash
### BEGIN INIT INFO
# Provides:          Apache Traffic Server
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apache Traffic Server
# Description:       This daemon will start the Apache Traffic Server
### END INIT INFO
#
# Apache Traffic Server daemon startup script
#
# created by NightBits (Jeroen Saey)
# description: Apache Traffic server daemon
#

if [[ ! $1 ]]; then
  echo "first input missing; example: `basename $0` [stop|start|restart|status|commit|condrestart|clearcache|stats]"
  exit 0
fi

# change this if option1 was chosen during installation to /usr/bin
trafficserverpath=/usr/local/bin

start() {
        echo "Starting Traffic Server"
        $trafficserverpath/trafficserver $operation
        }

stop() {
        echo "Stopping Traffic Server"
        $trafficserverpath/trafficserver $operation
        }

status() {
        echo "Status"
        $trafficserverpath/trafficserver $operation
        }

restart() {
        echo "Restarting Traffic Server"
        $trafficserverpath/trafficserver $operation
        }

commit() {
        echo "Committing changes"
        $trafficserverpath/traffic_line -x
        }

clearcache() {
        echo "Clearing cache"
        $trafficserverpath/trafficserver -C clear
        }

stats() {
echo System
echo -n hostname & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.hostname
echo -n Objects served & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.user_agents_total_documents_served
echo -n Transactions per second & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.user_agent_xacts_per_second
echo -n Document hit rate & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.cache_hit_ratio_avg_10s
echo -n Bandwidth savings & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.bandwidth_hit_ratio_avg_10s
echo -n Cache percent free & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.cache.percent_free
echo -n Open origin server connections & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.current_server_connections
echo -n Open client connections & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.current_client_connections
echo -n Cache transfers in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.current_cache_connections
echo -n Client throughput Mbits/sec & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.client_throughput_out
echo -n Transactions per second & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.user_agent_xacts_per_second
echo -n DNS lookups per second & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.dns.lookups_per_second
echo -n Host database hit rate & echo -n " " & $trafficserverpath/traffic_line -r proxy.node.hostdb.hit_ratio_avg_10s

echo HTTP
echo -n Total document bytes from client & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.user_agent_response_document_total_size
echo -n Total header bytes from client & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.user_agent_response_header_total_size
echo -n Total connections to client & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.total_client_connections
echo -n Client transactions in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.current_client_transactions
echo -n Total document bytes from origin server & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.origin_server_response_document_total_size
echo -n Total header bytes from origin server & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.origin_server_response_header_total_size
echo -n Total connections to origin server & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.total_server_connections
echo -n Origin server transactions in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.http.current_server_transactions

echo Cache
echo -n Bytes used & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.bytes_used
echo -n Cache size & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.bytes_total
echo -n Lookups in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.lookup.active
echo -n Lookups completed & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.lookup.success
echo -n Lookup misses & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.lookup.failure
echo -n Reads in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.read.active
echo -n Reads completed & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.read.success
echo -n Read misses & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.read.failure
echo -n Writes in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.write.active
echo -n Writes completed & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.write.success
echo -n Write failures & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.write.failure
echo -n Updates in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.update.active
echo -n Updates completed & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.update.success
echo -n Update failures & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.update.failure
echo -n Removes in progress & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.remove.active
echo -n Remove successes & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.remove.success
echo -n Remove failures & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.cache.remove.failure

echo Database
echo -n Total lookups & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.hostdb.total_lookups
echo -n Total hits & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.hostdb.total_hits
echo -n Time TTL min & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.hostdb.ttl

echo DNS
echo -n DNS total lookups & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.dns.total_dns_lookups
echo -n Average lookup time msec & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.dns.lookup_avg_time
echo -n DNS successes & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.dns.lookup_successes

echo Congestion
echo -n Number of congestions Traffic Server has observed because the maximum number of connections was exceeded. & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.congestion.congested_on_max_connection
echo -n Number of congestions Traffic Server has observed because of an OS response or timeout failure. & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.congestion.congested_on_conn_failures

echo Logging
echo -n Log files currently open & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.log.log_files_open
echo -n Space used for log files & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.log.log_files_space_used
echo -n Number of access events logged & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.log.event_log_access
echo -n Number of access events skipped & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.log.event_log_access_skip
echo -n Number of error events logged & echo -n " " & $trafficserverpath/traffic_line -r proxy.process.log.event_log_error

}


systemstats() {
echo System
$trafficserverpath/traffic_line -r proxy.node.hostname
$trafficserverpath/traffic_line -r proxy.node.user_agents_total_documents_served
$trafficserverpath/traffic_line -r proxy.node.user_agent_xacts_per_second
$trafficserverpath/traffic_line -r proxy.node.cache_hit_ratio_avg_10s
$trafficserverpath/traffic_line -r proxy.node.bandwidth_hit_ratio_avg_10s
$trafficserverpath/traffic_line -r proxy.node.cache.percent_free
$trafficserverpath/traffic_line -r proxy.node.current_server_connections
$trafficserverpath/traffic_line -r proxy.node.current_client_connections
$trafficserverpath/traffic_line -r proxy.node.current_cache_connections
$trafficserverpath/traffic_line -r proxy.node.client_throughput_out
$trafficserverpath/traffic_line -r proxy.node.user_agent_xacts_per_second
$trafficserverpath/traffic_line -r proxy.node.dns.lookups_per_second
$trafficserverpath/traffic_line -r proxy.node.hostdb.hit_ratio_avg_10s
        }

httpstats() {
echo HTTP
$trafficserverpath/traffic_line -r proxy.process.http.user_agent_response_document_total_size
$trafficserverpath/traffic_line -r proxy.process.http.user_agent_response_header_total_size
$trafficserverpath/traffic_line -r proxy.process.http.total_client_connections
$trafficserverpath/traffic_line -r proxy.process.http.current_client_transactions
$trafficserverpath/traffic_line -r proxy.process.http.origin_server_response_document_total_size
$trafficserverpath/traffic_line -r proxy.process.http.origin_server_response_header_total_size
$trafficserverpath/traffic_line -r proxy.process.http.total_server_connections
$trafficserverpath/traffic_line -r proxy.process.http.current_server_transactions
        }
cachestats() {
echo Cache
$trafficserverpath/traffic_line -r proxy.process.cache.bytes_used
$trafficserverpath/traffic_line -r proxy.process.cache.bytes_total
$trafficserverpath/traffic_line -r proxy.process.cache.lookup.active
$trafficserverpath/traffic_line -r proxy.process.cache.lookup.success
$trafficserverpath/traffic_line -r proxy.process.cache.lookup.failure
$trafficserverpath/traffic_line -r proxy.process.cache.read.active
$trafficserverpath/traffic_line -r proxy.process.cache.read.success
$trafficserverpath/traffic_line -r proxy.process.cache.read.failure
$trafficserverpath/traffic_line -r proxy.process.cache.write.active
$trafficserverpath/traffic_line -r proxy.process.cache.write.success
$trafficserverpath/traffic_line -r proxy.process.cache.write.failure
$trafficserverpath/traffic_line -r proxy.process.cache.update.active
$trafficserverpath/traffic_line -r proxy.process.cache.update.success
$trafficserverpath/traffic_line -r proxy.process.cache.update.failure
$trafficserverpath/traffic_line -r proxy.process.cache.remove.active
$trafficserverpath/traffic_line -r proxy.process.cache.remove.success
$trafficserverpath/traffic_line -r proxy.process.cache.remove.failure
        }

databasestats() {
echo Database
$trafficserverpath/traffic_line -r proxy.process.hostdb.total_lookups
$trafficserverpath/traffic_line -r proxy.process.hostdb.total_hits
$trafficserverpath/traffic_line -r proxy.process.hostdb.ttl
        }

dnsstats() {
echo DNS
$trafficserverpath/traffic_line -r proxy.process.dns.total_dns_lookups
$trafficserverpath/traffic_line -r proxy.process.dns.lookup_avg_time
$trafficserverpath/traffic_line -r proxy.process.dns.lookup_successes
        }

loggingstats() {
echo Logging
$trafficserverpath/traffic_line -r proxy.process.log.log_files_open
$trafficserverpath/traffic_line -r proxy.process.log.log_files_space_used
$trafficserverpath/traffic_line -r proxy.process.log.event_log_access
$trafficserverpath/traffic_line -r proxy.process.log.event_log_access_skip
$trafficserverpath/traffic_line -r proxy.process.log.event_log_error
        }

congestionstats() {
echo Congestion
$trafficserverpath/traffic_line -r proxy.process.congestion.congested_on_max_connection
$trafficserverpath/traffic_line -r proxy.process.congestion.congested_on_conn_failures
        }



case "$1" in
  start)
        operation=start
        start
        RETVAL=1
        exit
        ;;
  stop)
        operation=stop
        stop
        RETVAL=2
        exit
        ;;
  restart)
        operation=restart
        restart
        RETVAL=3
        exit
        ;;
  status)
        operation=status
        status
        RETVAL=4
        exit
        ;;

  commit)
        operation=-x
        commit
        RETVAL=10
        exit
        ;;

  clearcache)
        operation=clearcache
        clearcache
        RETVAL=5
        exit
        ;;
  stats)
        operation=stats
        stats
        RETVAL=20
        exit
        ;;
 systemstats)
        operation=systemstats
        systemstats
        RETVAL=21
        exit
        ;;
 httpstats)
        operation=httpstats
        httpstats
        RETVAL=22
        exit
        ;;
 cachestats)
        operation=cachestats
        cachestats
        RETVAL=23
        exit
        ;;
 databasestats)
        operation=databasestats
        databasestats
        RETVAL=24
        exit
        ;;
 dnsstats)
        operation=dnsstats
        dnsstats
        RETVAL=25
        exit
        ;;
 loggingstats)
        operation=loggingstats
        loggingstats
        RETVAL=26
        exit
        ;;
 congestionstats)
        operation=congestionstats
        congestionstats
        RETVAL=27
        exit
        ;;

  usage)
        operation=usage
        echo "input missing; example: `basename $0` [stop|start|restart|status|clearcache|stats]"
        RETVAL=-1
        exit
        ;;

  *)    ./`basename $0` usage
        RETVAL=-1
        exit
        ;;
esac
